class StaticData {
  static List<String> roomTypesCottage = ['Cottage', 'Room'];
  static List<String> provinces = [
    'Gauteng',
    'KwaZulu-Natal',
    'Eastern Cape',
    'Free State',
    'Limpopo',
    'Mpumalanga',
    'Northern Cape',
    'North West',
    'Western Cape'
  ];

  static List<String> cities = [
    'Johannesburg',
    'Vereeniging',
    'Pietermaritzburg',
    'Pretoria',
    'Durban',
    'Cape Town',
    'Welkom',
    'East London',
    'Randburg',
    'Roodepoort',
    'Port Elizabeth',
    'Bloemfontein',
    'Centurion',
    'Springs',
    'Sandton',
    'Polokwane',
    'Klerksdorp',
    'Rustenburg',
    'Kimberley',
    'Bhisho',
    'Benoni',
    'George',
    'Middelburg',
    'Vryheid',
    'Potchefstroom',
    'Umtata',
    'Brits',
    'Alberton',
    'Upington',
    'Paarl',
    'Queenstown',
    'Mmabatho',
    'Kroonstad',
    'Uitenhage',
    'Bethal',
    'Worcester',
    'Vanderbijlpark',
    'Grahamstown',
    'Standerton',
    'Brakpan',
    'Thohoyandou',
    'Saldanha',
    'Tzaneen',
    'Graaff-Reinet',
    'Oudtshoorn',
    'Mossel Bay',
    'Port Shepstone',
    'Knysna',
    'Vryburg',
    'Ladysmith',
    'Beaufort West',
    'Aliwal North',
    'Volksrust',
    'Musina',
    'Vredenburg',
    'Malmesbury',
    'Lebowakgomo',
    'Cradock',
    'De Aar',
    'Ulundi',
    'Jeffrey u2019s Bay',
    'Lichtenburg',
    'Hermanus',
    'Carletonville',
    'Komatipoort',
    'Middelburg',
    'Port Alfred',
    'Swellendam',
    'Bloemhof',
    'Bethlehem',
    'Montagu',
    'Mahikeng',
    'Bredasdorp',
    'Phalaborwa',
    'Caledon',
    'Moorreesburg',
    'Colesberg',
    'Brandfort',
    'Piketberg',
    'Saint Helena Bay',
    'Prieska',
    'Velddrif',
    'Springbok',
    'Darling',
    'Kuruman',
    'Villiersdorp',
    'Tulbagh',
    'Saron',
    'Clanwilliam',
    'Citrusdal',
    'Porterville',
    'Kleinmond',
    'Hopefield',
    'Vanrhynsdorp',
    'Klawer',
    'Lambert u2019s Bay',
    'Port Saint John u2019s',
    'Carnarvon',
    'Genadendal',
    'Riviersonderend',
    'Onrus',
    'Pofadder',
    'Barrydale',
    'Steytlerville',
    'Rawsonville',
    'Fraserburg',
    'Suurbraak',
    'Nelspruit',
  ];
}
